# Generated by Django 5.2.1 on 2025-06-14 17:21

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MumentUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('mu_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('idea_submission', models.TextField()),
                ('team', models.CharField(blank=True, max_length=50, null=True)),
                ('is_coordinator', models.BooleanField(default=False)),
                ('players_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'db_table': 'mument_user_table',
            },
        ),
    ]
