# Generated by Django 5.2.1 on 2025-06-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mumentuser',
            table='mument_users',
        ),
    ]
