# Generated by Django 5.2.1 on 2025-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mumentuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumentuser',
            name='coordinator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
