# Generated by Django 5.2.1 on 2025-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdate',
            name='uuid',
            field=models.UUIDField(editable=False),
        ),
    ]
