# Generated by Django 5.2.1 on 2025-06-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinator',
            table='coordinators',
        ),
    ]
