# Generated by Django 5.2.1 on 2025-06-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0002_alter_coordinator_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
