# Generated by Django 5.2.1 on 2025-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='name',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
