# Generated by Django 5.2.1 on 2025-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0005_remove_coordinator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
